# Generated by Django 5.1.6 on 2025-02-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250222_1817'),
    ]

    operations = [
    ]
